site_name: PySpring
site_url: https://mydomain.org/mysite
# Add the GitHub repository details
repo_url: https://github.com/PythonSpring/pyspring-core
repo_name: pyspring-core

theme:
  name: material
  features:
    - content.code.copy
    - navigation.expand
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

    

nav:
  - Overview: index.md
  - Guide:
      - Entityies In Framework:
          - Component: guide/entities-in-framework/component.md
          - Properties: guide/entities-in-framework/properties.md
          - REST Controller: guide/entities-in-framework/rest-controller.md
          - Bean Collection:  guide/entities-in-framework/bean-collection.md
      - Dependency Injection:
          - What is Dependency Injection: guide/dependency-injection/what-is-denpendency-injection.md
          - Auto Dependency Injection: guide/dependency-injection/auto-deppendency-injection.md
      - Event System:
          - Intro to Event System: guide/event-system/index.md
      - Middleware:
          - Middleware System: guide/middleware/index.md
      - Graceful Shutdown:
          - Graceful Shutdown: guide/graceful-shutdown/index.md
      - Scheduling:
          - Scheduler: guide/scheduling/scheduler.md
      - PySpringModel:
          - Overview: guide/pyspring-model/index.md
          - Dynamic Queries: guide/pyspring-model/dynamic-queries.md
          - Custom SQL Queries: guide/pyspring-model/custom-queries.md
          - CRUD Operations: guide/pyspring-model/crud-operations.md
          - Skip Auto Implementation: guide/pyspring-model/skip-auto-implementation.md
          - Complete Examples: guide/pyspring-model/examples.md
          - Deep Dive on SQL statement generation: guide/pyspring-model/sql-statement-algorithm.md
     
      
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences